### ISSUE TITLE
Passing variables to CLI

### ISSUE THREAD

**Issue by serrynaimo** [omairvaiyani/ghact-uilicious#1]
Hi Omair,

great work. Is there an option to pass variables to the CLI? E.g. the deployment path from a previous action?

**Comment by omairvaiyani** [comment]
@serrynaimo I believe instead of a bypass-approach, its best to add specific CLI params as Action inputs. Which inputs are you wanting? You could follow this [simple PR](https://github.com/omairvaiyani/ghact-uilicious/pull/2) to see how to expand the current available inputs.
